afi_autofilingModel.aspect.afi_autofilingRule.title=Autofiling Rule
afi_autofilingModel.aspect.afi_autofilingRule.description=Applied to autofiling rule nodes stored in the Data Dictionary

afi_autofilingModel.property.afi_enabled.title=Enabled
afi_autofilingModel.property.afi_inboxPath.title=Inbox Path
afi_autofilingModel.property.afi_contentType.title=Content Types
afi_autofilingModel.property.afi_priority.title=Priority
